FROM python:3.6-alpine

MAINTAINER Abhilash Raj

#Add startup script to container
COPY docker-entrypoint.sh /usr/local/bin/
COPY assets/postfix/main.cf.mod /usr/local/bin/

# Set the commits that we are building.
ARG CORE_REF
ARG MM3_HK_REF


#Install all required packages, add user for executing mailman and set execution
#rights for startup script
RUN apk update \
    && apk add --virtual build-deps gcc python3-dev musl-dev postgresql-dev git \
    && apk add bash su-exec postgresql-client mysql-client curl postfix \
    && pip install -U psycopg2 pymysql \
                      git+https://gitlab.com/mailman/mailman@${CORE_REF} \
											git+https://gitlab.com/mailman/mailman-hyperkitty@${MM3_HK_REF} \
    && apk del build-deps \
	&& apk del exim \
    && adduser -S mailman

# Change the working directory.
WORKDIR /opt/mailman

#Expose the ports for the api (8001) and lmtp (8024), smtp (25)
EXPOSE 8001 8024 25

# Set the default configuration file.
ENV MAILMAN_CONFIG_FILE /etc/mailman.cfg

ENTRYPOINT ["docker-entrypoint.sh"]

CMD ["master"]
